2020/04/20 20:27:46 [error] 24483#24483: *27 connect() to unix:/run/polls_django.sock failed (111: Connection refused) while connecting to upstream, client: 125.239.175.5, server: cinemanager.co.nz, request: "GET / HTTP/1.1", upstream: "http://unix:/run/polls_django.sock:/", host: "cinemanager.co.nz"
2020/04/20 20:27:46 [error] 24483#24483: *27 connect() to unix:/run/polls_django.sock failed (111: Connection refused) while connecting to upstream, client: 125.239.175.5, server: cinemanager.co.nz, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/run/polls_django.sock:/favicon.ico", host: "cinemanager.co.nz", referrer: "http://cinemanager.co.nz/"
